"""initial

Revision ID: 9aee75e5718b
Revises: 
Create Date: 2024-11-07 18:12:02.852398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aee75e5718b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spycat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spycat_breed'), 'spycat', ['breed'], unique=False)
    op.create_index(op.f('ix_spycat_id'), 'spycat', ['id'], unique=False)
    op.create_index(op.f('ix_spycat_name'), 'spycat', ['name'], unique=False)
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spy_cat_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['spy_cat_id'], ['spycat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_id'), 'mission', ['id'], unique=False)
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_id'), 'target', ['id'], unique=False)
    op.create_index(op.f('ix_target_name'), 'target', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_name'), table_name='target')
    op.drop_index(op.f('ix_target_id'), table_name='target')
    op.drop_table('target')
    op.drop_index(op.f('ix_mission_id'), table_name='mission')
    op.drop_table('mission')
    op.drop_index(op.f('ix_spycat_name'), table_name='spycat')
    op.drop_index(op.f('ix_spycat_id'), table_name='spycat')
    op.drop_index(op.f('ix_spycat_breed'), table_name='spycat')
    op.drop_table('spycat')
    # ### end Alembic commands ###
